[workspace]
resolver = "2"
members = [
    "x509-validator-core",
    "x509-validator",
    "x509-validator-testkit",
    "examples",
    "x509-validator-bench/compare",
    "x509-validator-bench/measure",
]

[workspace.package]
edition = "2024"

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(bench)",
    "cfg(coverage_nightly)",
    "cfg(rustls_docsrs)",
] }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"