[package]
name = "x509-validator-fuzz"
version = "0.0.1"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
x509-validator = { path = "../x509-validator", default-features = false }
x509-validator-fuzzing-provider = { path = "../x509-validator-fuzzing-provider" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parse_certificate"
path = "fuzzers/parse_certificate.rs"

[[bin]]
name = "validate_chain"
path = "fuzzers/validate_chain.rs"

[[bin]]
name = "server_identity"
path = "fuzzers/server_identity.rs"

[[bin]]
name = "name_constraints"
path = "fuzzers/name_constraints.rs"
