//! Confirms the vendored Mozilla CA bundle roots are correctly embedded as
//! DER for `benches/parse.rs`.
//!
//! The parsing benchmark uses `harness = false`, so a plain `#[test]`
//! placed inside it never runs under `cargo test` — divan's own `main`
//! drives that binary. This integration test duplicates the corpus list so
//! the completeness and parseability checks actually execute.

use x509_validator_core::{Certificate, FromDer};

static ROOTS: &[&[u8]] = &[
    include_bytes!("../data/mozilla/ACCVRAIZ1.der"),
    include_bytes!("../data/mozilla/AC_RAIZ_FNMT-RCM.der"),
    include_bytes!("../data/mozilla/AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.der"),
    include_bytes!("../data/mozilla/ANF_Secure_Server_Root_CA.der"),
    include_bytes!("../data/mozilla/Actalis_Authentication_Root_CA.der"),
    include_bytes!("../data/mozilla/AffirmTrust_Commercial.der"),
    include_bytes!("../data/mozilla/AffirmTrust_Networking.der"),
    include_bytes!("../data/mozilla/AffirmTrust_Premium.der"),
    include_bytes!("../data/mozilla/AffirmTrust_Premium_ECC.der"),
    include_bytes!("../data/mozilla/Amazon_Root_CA_1.der"),
    include_bytes!("../data/mozilla/Amazon_Root_CA_2.der"),
    include_bytes!("../data/mozilla/Amazon_Root_CA_3.der"),
    include_bytes!("../data/mozilla/Amazon_Root_CA_4.der"),
    include_bytes!("../data/mozilla/Atos_TrustedRoot_2011.der"),
    include_bytes!("../data/mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.der"),
    include_bytes!("../data/mozilla/Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068_2.der"),
    include_bytes!("../data/mozilla/Baltimore_CyberTrust_Root.der"),
    include_bytes!("../data/mozilla/Buypass_Class_2_Root_CA.der"),
    include_bytes!("../data/mozilla/Buypass_Class_3_Root_CA.der"),
    include_bytes!("../data/mozilla/CA_Disig_Root_R2.der"),
    include_bytes!("../data/mozilla/CFCA_EV_ROOT.der"),
    include_bytes!("../data/mozilla/COMODO_Certification_Authority.der"),
    include_bytes!("../data/mozilla/COMODO_ECC_Certification_Authority.der"),
    include_bytes!("../data/mozilla/COMODO_RSA_Certification_Authority.der"),
    include_bytes!("../data/mozilla/Certainly_Root_E1.der"),
    include_bytes!("../data/mozilla/Certainly_Root_R1.der"),
    include_bytes!("../data/mozilla/Certigna.der"),
    include_bytes!("../data/mozilla/Certigna_Root_CA.der"),
    include_bytes!("../data/mozilla/Certum_EC-384_CA.der"),
    include_bytes!("../data/mozilla/Certum_Trusted_Network_CA.der"),
    include_bytes!("../data/mozilla/Certum_Trusted_Network_CA_2.der"),
    include_bytes!("../data/mozilla/Certum_Trusted_Root_CA.der"),
    include_bytes!("../data/mozilla/Comodo_AAA_Services_root.der"),
    include_bytes!("../data/mozilla/D-TRUST_BR_Root_CA_1_2020.der"),
    include_bytes!("../data/mozilla/D-TRUST_EV_Root_CA_1_2020.der"),
    include_bytes!("../data/mozilla/D-TRUST_Root_Class_3_CA_2_2009.der"),
    include_bytes!("../data/mozilla/D-TRUST_Root_Class_3_CA_2_EV_2009.der"),
    include_bytes!("../data/mozilla/DigiCert_Assured_ID_Root_CA.der"),
    include_bytes!("../data/mozilla/DigiCert_Assured_ID_Root_G2.der"),
    include_bytes!("../data/mozilla/DigiCert_Assured_ID_Root_G3.der"),
    include_bytes!("../data/mozilla/DigiCert_Global_Root_CA.der"),
    include_bytes!("../data/mozilla/DigiCert_Global_Root_G2.der"),
    include_bytes!("../data/mozilla/DigiCert_Global_Root_G3.der"),
    include_bytes!("../data/mozilla/DigiCert_High_Assurance_EV_Root_CA.der"),
    include_bytes!("../data/mozilla/DigiCert_TLS_ECC_P384_Root_G5.der"),
    include_bytes!("../data/mozilla/DigiCert_TLS_RSA4096_Root_G5.der"),
    include_bytes!("../data/mozilla/DigiCert_Trusted_Root_G4.der"),
    include_bytes!("../data/mozilla/E-Tugra_Certification_Authority.der"),
    include_bytes!("../data/mozilla/E-Tugra_Global_Root_CA_ECC_v3.der"),
    include_bytes!("../data/mozilla/E-Tugra_Global_Root_CA_RSA_v3.der"),
    include_bytes!("../data/mozilla/Entrust.net_Premium_2048_Secure_Server_CA.der"),
    include_bytes!("../data/mozilla/Entrust_Root_Certification_Authority.der"),
    include_bytes!("../data/mozilla/Entrust_Root_Certification_Authority_-_EC1.der"),
    include_bytes!("../data/mozilla/Entrust_Root_Certification_Authority_-_G2.der"),
    include_bytes!("../data/mozilla/Entrust_Root_Certification_Authority_-_G4.der"),
    include_bytes!("../data/mozilla/GDCA_TrustAUTH_R5_ROOT.der"),
    include_bytes!("../data/mozilla/GLOBALTRUST_2020.der"),
    include_bytes!("../data/mozilla/GTS_Root_R1.der"),
    include_bytes!("../data/mozilla/GTS_Root_R2.der"),
    include_bytes!("../data/mozilla/GTS_Root_R3.der"),
    include_bytes!("../data/mozilla/GTS_Root_R4.der"),
    include_bytes!("../data/mozilla/GlobalSign_ECC_Root_CA_-_R4.der"),
    include_bytes!("../data/mozilla/GlobalSign_ECC_Root_CA_-_R5.der"),
    include_bytes!("../data/mozilla/GlobalSign_Root_CA.der"),
    include_bytes!("../data/mozilla/GlobalSign_Root_CA_-_R3.der"),
    include_bytes!("../data/mozilla/GlobalSign_Root_CA_-_R6.der"),
    include_bytes!("../data/mozilla/GlobalSign_Root_E46.der"),
    include_bytes!("../data/mozilla/GlobalSign_Root_R46.der"),
    include_bytes!("../data/mozilla/Go_Daddy_Class_2_CA.der"),
    include_bytes!("../data/mozilla/Go_Daddy_Root_Certificate_Authority_-_G2.der"),
    include_bytes!("../data/mozilla/HARICA_TLS_ECC_Root_CA_2021.der"),
    include_bytes!("../data/mozilla/HARICA_TLS_RSA_Root_CA_2021.der"),
    include_bytes!("../data/mozilla/Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.der"),
    include_bytes!("../data/mozilla/Hellenic_Academic_and_Research_Institutions_RootCA_2015.der"),
    include_bytes!("../data/mozilla/HiPKI_Root_CA_-_G1.der"),
    include_bytes!("../data/mozilla/Hongkong_Post_Root_CA_1.der"),
    include_bytes!("../data/mozilla/Hongkong_Post_Root_CA_3.der"),
    include_bytes!("../data/mozilla/ISRG_Root_X1.der"),
    include_bytes!("../data/mozilla/ISRG_Root_X2.der"),
    include_bytes!("../data/mozilla/IdenTrust_Commercial_Root_CA_1.der"),
    include_bytes!("../data/mozilla/IdenTrust_Public_Sector_Root_CA_1.der"),
    include_bytes!("../data/mozilla/Izenpe.com.der"),
    include_bytes!("../data/mozilla/Microsec_e-Szigno_Root_CA_2009.der"),
    include_bytes!("../data/mozilla/Microsoft_ECC_Root_Certificate_Authority_2017.der"),
    include_bytes!("../data/mozilla/Microsoft_RSA_Root_Certificate_Authority_2017.der"),
    include_bytes!("../data/mozilla/NAVER_Global_Root_Certification_Authority.der"),
    include_bytes!("../data/mozilla/NetLock_Arany_=Class_Gold=_Fotanusitvany.der"),
    include_bytes!("../data/mozilla/OISTE_WISeKey_Global_Root_GB_CA.der"),
    include_bytes!("../data/mozilla/OISTE_WISeKey_Global_Root_GC_CA.der"),
    include_bytes!("../data/mozilla/QuoVadis_Root_CA_1_G3.der"),
    include_bytes!("../data/mozilla/QuoVadis_Root_CA_2.der"),
    include_bytes!("../data/mozilla/QuoVadis_Root_CA_2_G3.der"),
    include_bytes!("../data/mozilla/QuoVadis_Root_CA_3.der"),
    include_bytes!("../data/mozilla/QuoVadis_Root_CA_3_G3.der"),
    include_bytes!("../data/mozilla/SSL.com_EV_Root_Certification_Authority_ECC.der"),
    include_bytes!("../data/mozilla/SSL.com_EV_Root_Certification_Authority_RSA_R2.der"),
    include_bytes!("../data/mozilla/SSL.com_Root_Certification_Authority_ECC.der"),
    include_bytes!("../data/mozilla/SSL.com_Root_Certification_Authority_RSA.der"),
    include_bytes!("../data/mozilla/SZAFIR_ROOT_CA2.der"),
    include_bytes!("../data/mozilla/SecureSign_RootCA11.der"),
    include_bytes!("../data/mozilla/SecureTrust_CA.der"),
    include_bytes!("../data/mozilla/Secure_Global_CA.der"),
    include_bytes!("../data/mozilla/Security_Communication_ECC_RootCA1.der"),
    include_bytes!("../data/mozilla/Security_Communication_RootCA2.der"),
    include_bytes!("../data/mozilla/Security_Communication_RootCA3.der"),
    include_bytes!("../data/mozilla/Security_Communication_Root_CA.der"),
    include_bytes!("../data/mozilla/Starfield_Class_2_CA.der"),
    include_bytes!("../data/mozilla/Starfield_Root_Certificate_Authority_-_G2.der"),
    include_bytes!("../data/mozilla/Starfield_Services_Root_Certificate_Authority_-_G2.der"),
    include_bytes!("../data/mozilla/SwissSign_Gold_CA_-_G2.der"),
    include_bytes!("../data/mozilla/SwissSign_Silver_CA_-_G2.der"),
    include_bytes!("../data/mozilla/T-TeleSec_GlobalRoot_Class_2.der"),
    include_bytes!("../data/mozilla/T-TeleSec_GlobalRoot_Class_3.der"),
    include_bytes!("../data/mozilla/TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.der"),
    include_bytes!("../data/mozilla/TWCA_Global_Root_CA.der"),
    include_bytes!("../data/mozilla/TWCA_Root_Certification_Authority.der"),
    include_bytes!("../data/mozilla/TeliaSonera_Root_CA_v1.der"),
    include_bytes!("../data/mozilla/Telia_Root_CA_v2.der"),
    include_bytes!("../data/mozilla/Trustwave_Global_Certification_Authority.der"),
    include_bytes!("../data/mozilla/Trustwave_Global_ECC_P256_Certification_Authority.der"),
    include_bytes!("../data/mozilla/Trustwave_Global_ECC_P384_Certification_Authority.der"),
    include_bytes!("../data/mozilla/TunTrust_Root_CA.der"),
    include_bytes!("../data/mozilla/UCA_Extended_Validation_Root.der"),
    include_bytes!("../data/mozilla/UCA_Global_G2_Root.der"),
    include_bytes!("../data/mozilla/USERTrust_ECC_Certification_Authority.der"),
    include_bytes!("../data/mozilla/USERTrust_RSA_Certification_Authority.der"),
    include_bytes!("../data/mozilla/XRamp_Global_CA_Root.der"),
    include_bytes!("../data/mozilla/certSIGN_ROOT_CA.der"),
    include_bytes!("../data/mozilla/certSIGN_Root_CA_G2.der"),
    include_bytes!("../data/mozilla/e-Szigno_Root_CA_2017.der"),
    include_bytes!("../data/mozilla/ePKI_Root_Certification_Authority.der"),
    include_bytes!("../data/mozilla/emSign_ECC_Root_CA_-_C3.der"),
    include_bytes!("../data/mozilla/emSign_ECC_Root_CA_-_G3.der"),
    include_bytes!("../data/mozilla/emSign_Root_CA_-_C1.der"),
    include_bytes!("../data/mozilla/emSign_Root_CA_-_G1.der"),
    include_bytes!("../data/mozilla/vTrus_ECC_Root_CA.der"),
    include_bytes!("../data/mozilla/vTrus_Root_CA.der"),
];

#[test]
fn every_root_parses_and_corpus_is_complete() {
    assert_eq!(ROOTS.len(), 137, "corpus should hold every vendored root");
    for der in ROOTS {
        let (_, certificate) = Certificate::from_der(der).expect("every vendored root parses");
        assert!(!certificate.tbs_certificate.subject.as_raw().is_empty());
    }
}
